import argparse
import difflib
import hashlib
import sys
from pathlib import Path
from zipfile import BadZipFile, ZipFile


ROOT = Path(__file__).resolve().parents[1]
DEPENDENCY_REPORT = ROOT / "app/build/reports/release-runtime-dependencies.txt"
SNAPSHOT = ROOT / "docs/release-runtime-dependencies.lock"
TRACKED_FILES = (
    ROOT / "LICENSE",
    ROOT / "NOTICE.md",
    ROOT / "docs/third-party-notices-inventory-2026-09-27.md",
    ROOT / "app/libs/sherpa-onnx-1.13.4-arm64.aar",
    ROOT / "app/src/main/java/com/hiosdra/hreader/adapter/ai/gemma/Gemma4E2bModel.kt",
    ROOT / "app/src/main/java/com/hiosdra/hreader/adapter/tts/TtsModelPackageCatalog.kt",
    ROOT / "app/src/main/assets/tts/NOTICE",
)
LICENSE_ASSETS = ROOT / "app/src/main/assets/licenses"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def expected_snapshot() -> str:
    if not DEPENDENCY_REPORT.is_file():
        raise ValueError(
            "Release dependency report is missing; run "
            "./gradlew :app:writeReleaseRuntimeDependencyReport first"
        )

    dependencies = sorted(
        line.strip()
        for line in DEPENDENCY_REPORT.read_text(encoding="utf-8").splitlines()
        if line.strip()
    )
    if not dependencies:
        raise ValueError("Release dependency report is empty")

    files = [path for path in TRACKED_FILES if path.is_file()]
    files.extend(sorted(path for path in LICENSE_ASSETS.rglob("*") if path.is_file()))
    missing = [path.relative_to(ROOT) for path in TRACKED_FILES if not path.is_file()]
    if missing:
        raise ValueError("Tracked release notice inputs are missing: " + ", ".join(map(str, missing)))

    lines = [
        "# Generated by tools/verify_release_notices.py --update after reviewing release notice changes.",
        "# The Gradle graph covers releaseRuntimeClasspath; file hashes cover native/model/license notice inputs.",
        "[releaseRuntimeClasspath]",
        *dependencies,
        "",
        "[releaseNoticeInputsSha256]",
    ]
    lines.extend(
        f"{sha256(path)}  {path.relative_to(ROOT).as_posix()}"
        for path in sorted(set(files))
    )
    return "\n".join(lines) + "\n"


def verify_aab(aab: Path) -> None:
    source_assets = {
        path.relative_to(ROOT / "app/src/main/assets").as_posix(): path
        for path in LICENSE_ASSETS.rglob("*")
        if path.is_file()
    }
    if not source_assets:
        raise ValueError(f"No source license assets found under {LICENSE_ASSETS}")

    try:
        with ZipFile(aab) as bundle:
            bundle_assets = set(bundle.namelist())
            missing = sorted(
                relative_path
                for relative_path in source_assets
                if f"base/assets/{relative_path}" not in bundle_assets
            )
            changed = sorted(
                relative_path
                for relative_path, source in source_assets.items()
                if f"base/assets/{relative_path}" in bundle_assets
                and hashlib.sha256(bundle.read(f"base/assets/{relative_path}")).hexdigest()
                != sha256(source)
            )
    except (BadZipFile, OSError) as error:
        raise ValueError(f"Could not read App Bundle {aab}: {error}") from error

    if missing:
        raise ValueError("License assets missing from App Bundle: " + ", ".join(missing))
    if changed:
        raise ValueError("License assets differ from the source files: " + ", ".join(changed))
    print(f"Verified {len(source_assets)} license assets in {aab.name} (SHA-256 {sha256(aab)})")


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--update", action="store_true")
    parser.add_argument("--aab", type=Path)
    args = parser.parse_args()

    try:
        generated = expected_snapshot()
        if args.update:
            SNAPSHOT.write_text(generated, encoding="utf-8")
            print(f"Updated {SNAPSHOT.relative_to(ROOT)}")
        else:
            current = SNAPSHOT.read_text(encoding="utf-8") if SNAPSHOT.is_file() else ""
            if current != generated:
                diff = difflib.unified_diff(
                    current.splitlines(),
                    generated.splitlines(),
                    fromfile=str(SNAPSHOT.relative_to(ROOT)),
                    tofile="resolved release notice inputs",
                    lineterm="",
                )
                print("\n".join(diff), file=sys.stderr)
                print(
                    "Release dependencies or notice inputs changed. Review the license and model notices, "
                    "then update the snapshot with tools/verify_release_notices.py --update.",
                    file=sys.stderr,
                )
                return 1
            print("Release dependency and notice-input snapshot is current")

        if args.aab:
            verify_aab(args.aab.resolve())
    except (OSError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
